# Generated by Django 3.2.8 on 2022-01-13 15:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameBoard', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), default=[None, None, None, None, None, None, None, None, None], size=9)),
                ('status', models.CharField(max_length=32, null=True)),
                ('nextPlayer', models.CharField(default='X', max_length=1)),
                ('xState', models.CharField(default='not_ready', max_length=16)),
                ('oState', models.CharField(default='not_ready', max_length=16)),
                ('winner', models.CharField(max_length=1, null=True)),
                ('playerO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='O', to='game.player')),
                ('playerX', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='x', to='game.player')),
            ],
        ),
    ]
