# Generated by Django 3.2.8 on 2022-01-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='playerO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_invited', to='game.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='playerX',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_created', to='game.player'),
        ),
    ]
