# Generated by Django 3.2.8 on 2022-01-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(default='waiting', max_length=32),
        ),
    ]
