# Generated by Django 3.2.8 on 2022-02-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_game_invitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('0', 'Waiting'), ('1', 'Ready'), ('2', 'Delete'), ('3', 'Finished')], default='WAITING', max_length=32),
        ),
    ]
