# Generated by Django 3.2.8 on 2022-02-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('READY', 'Ready'), ('DELETED', 'Deleted'), ('FINISHED', 'Finished')], default='WAITING', max_length=32),
        ),
    ]
