# Generated by Django 3.2.8 on 2022-02-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='oState',
            field=models.CharField(choices=[(0, 'WAITING'), (1, 'READY'), (2, 'DELETED'), (3, 'FINISHED')], default='NOT_READY', max_length=16),
        ),
        migrations.AlterField(
            model_name='game',
            name='xState',
            field=models.CharField(choices=[(0, 'WAITING'), (1, 'READY'), (2, 'DELETED'), (3, 'FINISHED')], default='NOT_READY', max_length=16),
        ),
    ]
