# Generated by Django 3.2.8 on 2022-02-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20220204_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='oState',
            field=models.CharField(choices=[(0, 'NOT_READY'), (1, 'JOINED'), (2, 'LEAVED')], default='NOT_READY', max_length=16),
        ),
        migrations.AlterField(
            model_name='game',
            name='xState',
            field=models.CharField(choices=[(0, 'NOT_READY'), (1, 'JOINED'), (2, 'LEAVED')], default='NOT_READY', max_length=16),
        ),
    ]
