# Generated by Django 3.2.8 on 2022-02-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20220204_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='nextPlayer',
            field=models.CharField(choices=[(0, 'PLAYER_X'), (1, 'PLAYER_O')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(choices=[(0, 'PLAYER_X'), (1, 'PLAYER_O')], max_length=1, null=True),
        ),
    ]
