# Generated by Django 3.2.8 on 2022-02-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20220204_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[(0, 'WAITING'), (1, 'READY'), (2, 'DELETED'), (3, 'FINISHED')], max_length=32),
        ),
    ]
