# Generated by Django 3.2.8 on 2022-02-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(choices=[(0, 'X'), (1, 'O'), (3, 'DRAW')], max_length=1, null=True),
        ),
    ]
