# Generated by Django 3.2.8 on 2022-02-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_game_nextplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(choices=[(0, 'PLAYER_X'), (1, 'PLAYER_O'), (3, 'DRAW')], max_length=1, null=True),
        ),
    ]
