# Generated by Django 3.2.8 on 2022-02-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='nextPlayer',
            field=models.CharField(choices=[('PLAYER_X', 'PLAYER_X'), ('PLAYER_O', 'PLAYER_O')], default='PLAYER_X', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(choices=[('PLAYER_X', 'PLAYER_X'), ('PLAYER_O', 'PLAYER_O'), ('DRAW', 'DRAW')], max_length=20, null=True),
        ),
    ]
