# Generated by Django 3.2.8 on 2022-02-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_auto_20220215_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='nextPlayer',
            field=models.PositiveIntegerField(choices=[(0, 'PLAYER_X'), (1, 'PLAYER_O')], default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'WAITING'), (1, 'READY'), (2, 'DELETED'), (3, 'FINISHED')], max_length=32),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.PositiveIntegerField(choices=[(0, 'PLAYER_X'), (1, 'PLAYER_O'), (3, 'DRAW')], max_length=1, null=True),
        ),
    ]
