# Generated by Django 3.2.8 on 2022-02-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20220215_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='oState',
            field=models.PositiveIntegerField(choices=[(0, 'NOT_READY'), (1, 'JOINED'), (2, 'LEAVED')], default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='game',
            name='xState',
            field=models.PositiveIntegerField(choices=[(0, 'NOT_READY'), (1, 'JOINED'), (2, 'LEAVED')], default=0, max_length=16),
        ),
    ]
