# Generated by Django 3.2.8 on 2022-02-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_auto_20220215_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='nextPlayer',
            field=models.PositiveIntegerField(choices=[(0, 'PLAYER_X'), (1, 'PLAYER_O')], default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='oState',
            field=models.PositiveIntegerField(choices=[(0, 'NOT_READY'), (1, 'JOINED'), (2, 'LEAVED')], default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'WAITING'), (1, 'READY'), (2, 'DELETED'), (3, 'FINISHED')]),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.PositiveIntegerField(choices=[(0, 'PLAYER_X'), (1, 'PLAYER_O'), (3, 'DRAW')], null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='xState',
            field=models.PositiveIntegerField(choices=[(0, 'NOT_READY'), (1, 'JOINED'), (2, 'LEAVED')], default=0),
        ),
    ]
