# Generated by Django 3.2.6 on 2021-11-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_myuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
        migrations.AlterModelTable(
            name='myuser',
            table='tbl_users',
        ),
    ]
